#include "Enclave_u.h" // Generated by sgx_edger8r from EDL
#include "sgx_urts.h"
#include <stdio.h>

sgx_enclave_id_t eid;

void host_print(const char *str) {
  printf("[Host RECEIVED MESSAGE FROM ENCLAVE:] %s\n", str);
}

int main() {
  sgx_launch_token_t token = {0};
  int updated = 0;

  // Create enclave
  if (sgx_create_enclave("enclave.signed.so", SGX_DEBUG_FLAG, &token, &updated,
                         &eid, NULL) != SGX_SUCCESS) {
    printf("Failed to create enclave\n");
    return 1;
  }

  // user input
  int a, b;

  printf("Enter the first number: ");
  if (scanf("%d", &a) != 1) {
    printf("Invalid input!\n");
    return 1;
  }

  printf("Enter the second number: ");
  if (scanf("%d", &b) != 1) {
    printf("Invalid input!\n");
    return 1;
  }

  int init_value = 0;
  int *result = &init_value;
  enclave_add(eid, result, a, b); // ECALL
  printf("Result from enclave: %d\n", *result);

  sgx_destroy_enclave(eid);
  return 0;
}
