#include "Enclave_t.h"  // Generated by sgx_edger8r from EDL
#include <string.h>

int enclave_add(int a, int b) {
    char buf[100] = "Hello from enclave";
    host_print(buf);  // OCALL
    return a + b;
}
